-- MySQL Script generated by MySQL Workbench
-- Wed Oct 26 19:52:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `sistema` ;

-- -----------------------------------------------------
-- Table `sistema`.`privilegios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`privilegios` (
  `identificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`identificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `sistema`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`usuarios` (
  `identificacion` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(255) NOT NULL,
  `clave` TEXT NOT NULL,
  `privilegio` INT(11) NOT NULL,
  `foto` TEXT NULL DEFAULT NULL,
  `ultima_sesion` DATETIME NULL DEFAULT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`identificacion`),
  INDEX `users_fk_1` (`privilegio` ASC) VISIBLE,
  CONSTRAINT `users_fk_1`
    FOREIGN KEY (`privilegio`)
    REFERENCES `sistema`.`privilegios` (`identificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`auditoria` (
  `identificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(10) NOT NULL,
  `modulo` VARCHAR(50) NOT NULL,
  `accion` VARCHAR(50) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`identificacion`),
  INDEX `audit_fk_1` (`usuario` ASC) VISIBLE,
  CONSTRAINT `audit_fk_1`
    FOREIGN KEY (`usuario`)
    REFERENCES `sistema`.`usuarios` (`identificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`marcas` (
  `identificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(200) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`identificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`categorias` (
  `identificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(200) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`identificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`monedas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`monedas` (
  `identificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `moneda` VARCHAR(50) NOT NULL,
  `simbolo` VARCHAR(5) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`identificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`precio_monedas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`precio_monedas` (
  `identificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `moneda_principal` INT(11) NOT NULL,
  `moneda_secundaria` INT(11) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`identificacion`),
  INDEX `coin_prices_ibfk_1` (`moneda_principal` ASC) VISIBLE,
  INDEX `coin_prices_ibfk_2` (`moneda_secundaria` ASC) VISIBLE,
  CONSTRAINT `coin_prices_fk_1`
    FOREIGN KEY (`moneda_principal`)
    REFERENCES `sistema`.`monedas` (`identificacion`),
  CONSTRAINT `coin_prices_fk_2`
    FOREIGN KEY (`moneda_secundaria`)
    REFERENCES `sistema`.`monedas` (`identificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`clientes` (
  `identificacion` VARCHAR(12) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `direccion` TEXT NOT NULL,
  `telefono` VARCHAR(11) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`identificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`tipo_documento` (
  `identificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`identificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `sistema`.`impuestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`impuestos` (
  `identificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `impuesto` VARCHAR(50) NOT NULL,
  `porcentaje` INT(11) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`identificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`productos` (
  `codigo` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `marca` INT(11) NOT NULL,
  `categoria` INT(11) NOT NULL,
  `moneda` INT(11) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `impuesto` INT(11) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`codigo`),
  INDEX `brand` (`marca` ASC) VISIBLE,
  INDEX `category` (`categoria` ASC) VISIBLE,
  INDEX `coin` (`moneda` ASC) VISIBLE,
  INDEX `tax` (`impuesto` ASC) VISIBLE,
  CONSTRAINT `products_fk_1`
    FOREIGN KEY (`marca`)
    REFERENCES `sistema`.`marcas` (`identificacion`),
  CONSTRAINT `products_fk_2`
    FOREIGN KEY (`categoria`)
    REFERENCES `sistema`.`categorias` (`identificacion`),
  CONSTRAINT `products_fk_3`
    FOREIGN KEY (`moneda`)
    REFERENCES `sistema`.`monedas` (`identificacion`),
  CONSTRAINT `products_fk_4`
    FOREIGN KEY (`impuesto`)
    REFERENCES `sistema`.`impuestos` (`identificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`inventario` (
  `producto` VARCHAR(50) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`producto`),
  CONSTRAINT `inventory_fk_1`
    FOREIGN KEY (`producto`)
    REFERENCES `sistema`.`productos` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`proveedores` (
  `codigo` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `identificacion` VARCHAR(12) NOT NULL,
  `direccion` TEXT NOT NULL,
  `telefono` VARCHAR(11) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`compras` (
  `identificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `proveedor` VARCHAR(12) NOT NULL,
  `usuario` VARCHAR(10) NOT NULL,
  `fecha` DATE NOT NULL,
  `tipo_documento` INT(11) NOT NULL,
  `referencia` VARCHAR(25) NOT NULL,
  `moneda` INT(11) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`identificacion`),
  INDEX `purchases_ibfk_3` (`moneda` ASC) VISIBLE,
  INDEX `purchases_fk_1` (`proveedor` ASC) VISIBLE,
  INDEX `purchases_fk_2` (`usuario` ASC) VISIBLE,
  INDEX `purchases_fk_3` (`tipo_documento` ASC) VISIBLE,
  CONSTRAINT `purchases_fk_1`
    FOREIGN KEY (`proveedor`)
    REFERENCES `sistema`.`proveedores` (`codigo`),
  CONSTRAINT `purchases_fk_2`
    FOREIGN KEY (`usuario`)
    REFERENCES `sistema`.`usuarios` (`identificacion`),
  CONSTRAINT `purchases_fk_3`
    FOREIGN KEY (`tipo_documento`)
    REFERENCES `sistema`.`tipo_documento` (`identificacion`),
  CONSTRAINT `purchases_fk_4`
    FOREIGN KEY (`moneda`)
    REFERENCES `sistema`.`monedas` (`identificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`detalle_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`detalle_compra` (
  `identificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(50) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `compra` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`identificacion`),
  INDEX `purchase_details_ibfk_2` (`compra` ASC) VISIBLE,
  INDEX `fk_detalle_compra_products1_idx` (`producto` ASC) VISIBLE,
  CONSTRAINT `purchase_details_ibfk_2`
    FOREIGN KEY (`compra`)
    REFERENCES `sistema`.`compras` (`identificacion`),
  CONSTRAINT `fk_detalle_compra_products1`
    FOREIGN KEY (`producto`)
    REFERENCES `sistema`.`productos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`ventas` (
  `identificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `cliente` VARCHAR(12) NOT NULL,
  `usuario` VARCHAR(10) NOT NULL,
  `fecha` DATE NOT NULL,
  `tipo_documento` INT(11) NOT NULL,
  `moneda` INT(11) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`identificacion`),
  INDEX `sales_fk_1` (`cliente` ASC) VISIBLE,
  INDEX `sales_fk_2` (`usuario` ASC) VISIBLE,
  INDEX `sales_fk_3` (`tipo_documento` ASC) VISIBLE,
  INDEX `sales_fk_4` (`moneda` ASC) VISIBLE,
  CONSTRAINT `sales_fk_1`
    FOREIGN KEY (`cliente`)
    REFERENCES `sistema`.`clientes` (`identificacion`),
  CONSTRAINT `sales_fk_2`
    FOREIGN KEY (`usuario`)
    REFERENCES `sistema`.`usuarios` (`identificacion`),
  CONSTRAINT `sales_fk_3`
    FOREIGN KEY (`tipo_documento`)
    REFERENCES `sistema`.`tipo_documento` (`identificacion`),
  CONSTRAINT `sales_fk_4`
    FOREIGN KEY (`moneda`)
    REFERENCES `sistema`.`monedas` (`identificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`detalle_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`detalle_ventas` (
  `identificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(50) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `venta` INT(11) NOT NULL,
  PRIMARY KEY (`identificacion`),
  INDEX `sales_details_ibfk_2` (`venta` ASC) VISIBLE,
  INDEX `fk_detalle_ventas_productos1_idx` (`producto` ASC) VISIBLE,
  CONSTRAINT `sales_details_ibfk_2`
    FOREIGN KEY (`venta`)
    REFERENCES `sistema`.`ventas` (`identificacion`),
  CONSTRAINT `fk_detalle_ventas_productos1`
    FOREIGN KEY (`producto`)
    REFERENCES `sistema`.`productos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
