-- MySQL Script generated by MySQL Workbench
-- Sat Nov 26 10:41:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`metodo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`metodo_pago` (
  `id_metodo_pago` INT NOT NULL,
  `nom_metodo_pago` VARCHAR(50) NULL,
  `estado_metodo_pago` TINYINT(1) NULL DEFAULT 1,
  `actualizado_en` TIMESTAMP NULL,
  `creado_en` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_metodo_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`configuracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`configuracion` (
  `id_configuracion` INT NOT NULL AUTO_INCREMENT,
  `nom_configuracion` VARCHAR(45) NULL,
  `valor_configuracion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_configuracion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ancho_caucho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ancho_caucho` (
  `id_ancho_caucho` INT NOT NULL AUTO_INCREMENT,
  `ancho_numero` INT NULL,
  `estado_ancho_caucho` TINYINT(1) NULL DEFAULT 1,
  `actualizado_en` TIMESTAMP NULL,
  `creado_en` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_ancho_caucho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alto_caucho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alto_caucho` (
  `id_alto_caucho` INT NOT NULL AUTO_INCREMENT,
  `alto_numero` INT NULL,
  `estado_alto_caucho` TINYINT(1) NULL DEFAULT 1,
  `actualizado_en` TIMESTAMP NULL,
  `creado_en` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_alto_caucho`))
ENGINE = InnoDB;

USE `sistema` ;

-- -----------------------------------------------------
-- Table `sistema`.`privilegio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`privilegio` (
  `id_privilegio` INT(11) NOT NULL AUTO_INCREMENT,
  `nom_privilegio` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `estado_privilegio` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_privilegio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `sistema`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`usuario` (
  `ci_usuario` VARCHAR(8) NOT NULL,
  `nom_usuario` VARCHAR(50) NOT NULL,
  `clave_usuario` TEXT NOT NULL,
  `id_privilegio` INT(11) NOT NULL,
  `foto_usuario` TEXT NULL DEFAULT NULL,
  `ultima_sesion` DATETIME NULL DEFAULT NULL,
  `estado_usuario` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ci_usuario`),
  INDEX `users_fk_1` (`id_privilegio` ASC) VISIBLE,
  CONSTRAINT `users_fk_1`
    FOREIGN KEY (`id_privilegio`)
    REFERENCES `sistema`.`privilegio` (`id_privilegio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`auditoria` (
  `id_auditoria` INT(11) NOT NULL,
  `ci_usuario` VARCHAR(8) NOT NULL,
  `modulo_auditoria` VARCHAR(50) NOT NULL,
  `accion_auditoria` VARCHAR(50) NOT NULL,
  `desc_auditoria` TEXT NOT NULL,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_auditoria`),
  INDEX `audit_fk_1` (`ci_usuario` ASC) VISIBLE,
  CONSTRAINT `audit_fk_1`
    FOREIGN KEY (`ci_usuario`)
    REFERENCES `sistema`.`usuario` (`ci_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`marca` (
  `id_marca` INT(11) NOT NULL AUTO_INCREMENT,
  `nom_marca` VARCHAR(50) NOT NULL,
  `estado_marca` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`categoria` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nom_categoria` VARCHAR(50) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`moneda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`moneda` (
  `id_moneda` INT(11) NOT NULL AUTO_INCREMENT,
  `nom_moneda` VARCHAR(50) NOT NULL,
  `simbolo_moneda` VARCHAR(5) NOT NULL,
  `estado_moneda` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_moneda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`precio_moneda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`precio_moneda` (
  `id_precio_moneda` INT(11) NOT NULL AUTO_INCREMENT,
  `id_moneda_principal` INT(11) NOT NULL,
  `id_moneda_secundaria` INT(11) NOT NULL,
  `precio_moneda_primaria` DECIMAL(6,2) NOT NULL,
  `estado_precio_moneda` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_precio_moneda`),
  INDEX `coin_prices_ibfk_1` (`id_moneda_principal` ASC) VISIBLE,
  INDEX `coin_prices_ibfk_2` (`id_moneda_secundaria` ASC) VISIBLE,
  CONSTRAINT `coin_prices_fk_1`
    FOREIGN KEY (`id_moneda_principal`)
    REFERENCES `sistema`.`moneda` (`id_moneda`),
  CONSTRAINT `coin_prices_fk_2`
    FOREIGN KEY (`id_moneda_secundaria`)
    REFERENCES `sistema`.`moneda` (`id_moneda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`cliente` (
  `ci_rif_cliente` VARCHAR(11) NOT NULL,
  `nom_cliente` VARCHAR(50) NOT NULL,
  `direc_cliente` TEXT NOT NULL,
  `tlf_cliente` VARCHAR(11) NOT NULL,
  `estado_cliente` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ci_rif_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`tipo_documento` (
  `id_tipo_documento` INT(11) NOT NULL AUTO_INCREMENT,
  `nom_tipo_documento` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `estado_tipo_documento` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_tipo_documento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `sistema`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`producto` (
  `cod_producto` INT GENERATED ALWAYS AS () VIRTUAL,
  `nom_producto` VARCHAR(50) NOT NULL,
  `id_ancho_caucho` INT NOT NULL,
  `id_alto_caucho` INT NOT NULL,
  `id_categoria` INT(11) NOT NULL,
  `id_marca` INT(11) NOT NULL,
  `precio_producto` DECIMAL(13,2) NOT NULL,
  `cant_producto` INT(5) NOT NULL,
  `estado_producto` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cod_producto`),
  INDEX `brand` (`id_marca` ASC) VISIBLE,
  INDEX `category` (`id_categoria` ASC) VISIBLE,
  INDEX `fk_producto_ancho_caucho1_idx` (`id_ancho_caucho` ASC) VISIBLE,
  INDEX `fk_producto_alto_caucho1_idx` (`id_alto_caucho` ASC) VISIBLE,
  CONSTRAINT `products_fk_1`
    FOREIGN KEY (`id_marca`)
    REFERENCES `sistema`.`marca` (`id_marca`),
  CONSTRAINT `products_fk_2`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `sistema`.`categoria` (`id_categoria`),
  CONSTRAINT `fk_producto_ancho_caucho1`
    FOREIGN KEY (`id_ancho_caucho`)
    REFERENCES `mydb`.`ancho_caucho` (`id_ancho_caucho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_alto_caucho1`
    FOREIGN KEY (`id_alto_caucho`)
    REFERENCES `mydb`.`alto_caucho` (`id_alto_caucho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`inventario` (
  `producto` VARCHAR(50) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`producto`),
  CONSTRAINT `inventory_fk_1`
    FOREIGN KEY (`producto`)
    REFERENCES `sistema`.`producto` (`cod_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`proveedor` (
  `ci_rif_proveedor` VARCHAR(11) NOT NULL,
  `nom_proveedor` VARCHAR(50) NOT NULL,
  `direc_proveedor` TEXT NOT NULL,
  `tlf_proveedor` VARCHAR(11) NOT NULL,
  `estado_proveedor` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ci_rif_proveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`compra` (
  `id_compra` INT(11) NOT NULL AUTO_INCREMENT,
  `cod_proveedor` VARCHAR(11) NOT NULL,
  `ci_usuario` VARCHAR(8) NOT NULL,
  `fecha_compra` DATE NOT NULL,
  `id_tipo_documento` INT(11) NOT NULL,
  `ref_compra` VARCHAR(10) NOT NULL,
  `id_moneda` INT(11) NOT NULL,
  `total_compra` DECIMAL(13,2) NOT NULL,
  `estado_compra` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_compra`),
  INDEX `purchases_ibfk_3` (`id_moneda` ASC) VISIBLE,
  INDEX `purchases_fk_2` (`ci_usuario` ASC) VISIBLE,
  INDEX `purchases_fk_3` (`id_tipo_documento` ASC) VISIBLE,
  INDEX `purchases_fk_1_idx` (`cod_proveedor` ASC) VISIBLE,
  CONSTRAINT `purchases_fk_2`
    FOREIGN KEY (`ci_usuario`)
    REFERENCES `sistema`.`usuario` (`ci_usuario`),
  CONSTRAINT `purchases_fk_3`
    FOREIGN KEY (`id_tipo_documento`)
    REFERENCES `sistema`.`tipo_documento` (`id_tipo_documento`),
  CONSTRAINT `purchases_fk_4`
    FOREIGN KEY (`id_moneda`)
    REFERENCES `sistema`.`moneda` (`id_moneda`),
  CONSTRAINT `purchases_fk_1`
    FOREIGN KEY (`cod_proveedor`)
    REFERENCES `sistema`.`proveedor` (`ci_rif_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`detalle_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`detalle_compra` (
  `id_detalle_compra` INT(11) NOT NULL AUTO_INCREMENT,
  `cod_producto` INT NOT NULL,
  `cant_producto` INT(11) NOT NULL,
  `precio_producto` DECIMAL(13,2) NOT NULL DEFAULT '0.00',
  `id_compra` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_detalle_compra`),
  INDEX `purchase_details_ibfk_2` (`id_compra` ASC) VISIBLE,
  INDEX `fk_detalle_compra_products1_idx` (`cod_producto` ASC) VISIBLE,
  CONSTRAINT `purchase_details_ibfk_2`
    FOREIGN KEY (`id_compra`)
    REFERENCES `sistema`.`compra` (`id_compra`),
  CONSTRAINT `fk_detalle_compra_products1`
    FOREIGN KEY (`cod_producto`)
    REFERENCES `sistema`.`producto` (`cod_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`impuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`impuesto` (
  `id_impuesto` INT(11) NOT NULL AUTO_INCREMENT,
  `nom_impuesto` VARCHAR(50) NOT NULL,
  `porcent_impuesto` INT(11) NOT NULL,
  `estado_impuesto` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_impuesto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`venta` (
  `id_venta` INT(11) NOT NULL AUTO_INCREMENT,
  `ci_rif_cliente` VARCHAR(11) NOT NULL,
  `ci_usuario` VARCHAR(8) NOT NULL,
  `id_tipo_documento` INT(11) NOT NULL,
  `id_moneda` INT(11) NOT NULL,
  `tasa` DECIMAL(13,2) NULL,
  `id_impuesto` INT(11) NOT NULL,
  `id_metodo_pago` INT NOT NULL,
  `total_venta` DECIMAL(13,2) NOT NULL,
  `estado_venta` TINYINT(1) NOT NULL DEFAULT '1',
  `actualizado_en` TIMESTAMP NOT NULL,
  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_venta`),
  INDEX `sales_fk_1` (`ci_rif_cliente` ASC) VISIBLE,
  INDEX `sales_fk_2` (`ci_usuario` ASC) VISIBLE,
  INDEX `sales_fk_3` (`id_tipo_documento` ASC) VISIBLE,
  INDEX `sales_fk_4` (`id_moneda` ASC) VISIBLE,
  INDEX `fk_venta_impuesto1_idx` (`id_impuesto` ASC) VISIBLE,
  INDEX `fk_venta_metodo_pago1_idx` (`id_metodo_pago` ASC) VISIBLE,
  CONSTRAINT `sales_fk_1`
    FOREIGN KEY (`ci_rif_cliente`)
    REFERENCES `sistema`.`cliente` (`ci_rif_cliente`),
  CONSTRAINT `sales_fk_2`
    FOREIGN KEY (`ci_usuario`)
    REFERENCES `sistema`.`usuario` (`ci_usuario`),
  CONSTRAINT `sales_fk_3`
    FOREIGN KEY (`id_tipo_documento`)
    REFERENCES `sistema`.`tipo_documento` (`id_tipo_documento`),
  CONSTRAINT `sales_fk_4`
    FOREIGN KEY (`id_moneda`)
    REFERENCES `sistema`.`moneda` (`id_moneda`),
  CONSTRAINT `fk_venta_impuesto1`
    FOREIGN KEY (`id_impuesto`)
    REFERENCES `sistema`.`impuesto` (`id_impuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_metodo_pago1`
    FOREIGN KEY (`id_metodo_pago`)
    REFERENCES `mydb`.`metodo_pago` (`id_metodo_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`detalle_venta` (
  `id_detalle_venta` INT(11) NOT NULL AUTO_INCREMENT,
  `cod_producto` INT NOT NULL,
  `cant_producto` INT(11) NOT NULL,
  `precio_producto` DECIMAL(13,2) NOT NULL,
  `id_venta` INT(11) NOT NULL,
  PRIMARY KEY (`id_detalle_venta`),
  INDEX `sales_details_ibfk_2` (`id_venta` ASC) VISIBLE,
  INDEX `fk_detalle_ventas_productos1_idx` (`cod_producto` ASC) VISIBLE,
  CONSTRAINT `sales_details_ibfk_2`
    FOREIGN KEY (`id_venta`)
    REFERENCES `sistema`.`venta` (`id_venta`),
  CONSTRAINT `fk_detalle_ventas_productos1`
    FOREIGN KEY (`cod_producto`)
    REFERENCES `sistema`.`producto` (`cod_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
